name: GenlifeLogFilter
api: "1.21.4"
version: 1.0.0
main: me.fliqq.logfilter.PaperLightLogFilter
description: plugin de filtre de log léger pour paper
author: Fliqq
api-version: "1.21.4"
softdepend: []
commands:
  reloadlogfilter:
    permission: "logfilter.reload"
    default: false
    description: Recharger les configurations du filtre de log
