name: GenlifeLogFilter
api: "1.21.4"
version: 1.0.0
main: me.fliqq.logfilter.GenlifeLogFilter
description: plugin de filtre de log
author: Fliqq
api-version: "1.21.4"
softdepend: []
commands:
  reloadlogfilter:
    permission: "genlife.filter"
    default: false
    description: Recharger les configurations du filtre de log
